admin_page/urls.py
from django.urls import path

from admin_page.apps import AdminConfig
from admin_page.views import (AdminPageViews, EmployeeCreate, EmployeeDelete, EmployeeDetail, EmployeeList,
                              EmployeeUpdate, RestaurantDetail, RestaurantUpdate)

app_name = AdminConfig.name

urlpatterns = [
    path("admin_page/", AdminPageViews.as_view(), name="admin_page"),
    path("employee/", EmployeeList.as_view(), name="employee_list"),
    path("employee/<int:pk>/", EmployeeDetail.as_view(), name="employee_detail"),
    path("employee/create/", EmployeeCreate.as_view(), name="employee_create"),
    path("employee/<int:pk>/delete/", EmployeeDelete.as_view(), name="employee_delete"),
    path("employee/<int:pk>/update/", EmployeeUpdate.as_view(), name="employee_update"),
    path("restaurant/<int:pk>/update/", RestaurantUpdate.as_view(), name="restaurant_update"),
    path("restaurant/<int:pk>/", RestaurantDetail.as_view(), name="restaurant_detail"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
    path("", include("reservation.urls", namespace="reservation")),
    path("admin_page/", include("admin_page.urls", namespace="admin_page")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reservation/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from reservation.apps import ReservationConfig
from reservation.views import (AboutRestaurantViews, HomeViews, ReservationCreate, ReservationDelete,
                               ReservationDetail, ReservationList, ReservationUpdate, TableCreate, TableDelete,
                               TableDetail, TableList, TableUpdate, get_available_tables)

app_name = ReservationConfig.name

urlpatterns = [
    path("", HomeViews.as_view(), name="home"),
    path("restaurant/", cache_page(60 * 10)(AboutRestaurantViews.as_view()), name="restaurant"),
    path("reservation/create/", ReservationCreate.as_view(), name="reservation_create"),
    path("reservation/<int:pk>/", ReservationDetail.as_view(), name="reservation_detail"),
    path("reservation/<int:pk>/update/", ReservationUpdate.as_view(), name="reservation_update"),
    path("reservation/<int:pk>/delete/", ReservationDelete.as_view(), name="reservation_delete"),
    path("reservation/", ReservationList.as_view(), name="reservation_list"),
    path("tables/", TableList.as_view(), name="table_list"),
    path("table/<int:pk>/", TableDetail.as_view(), name="table_detail"),
    path("table/create/", TableCreate.as_view(), name="table_create"),
    path("table/<int:pk>/delete/", TableDelete.as_view(), name="table_delete"),
    path("table/<int:pk>/update/", TableUpdate.as_view(), name="table_update"),
    path("get-available-tables/", get_available_tables, name="get_available_tables"),
]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordResetDoneView, PasswordResetView)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (BlockUsersView, UserCreateViews, UserDelete, UserDetail, UserList, UserUpdateViews,
                         email_verification)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateViews.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("users/<int:pk>/update", UserUpdateViews.as_view(), name="user_update"),
    path("users/<int:pk>/delete", UserDelete.as_view(), name="user_delete"),
    path("users/<int:pk>/", UserDetail.as_view(), name="user_detail"),
    path("users/", UserList.as_view(), name="user_list"),
    path("users/<int:pk>/block_user", BlockUsersView.as_view(), name="block_user"),
]

reservation/forms.py
from datetime import date

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
from phonenumber_field.formfields import PhoneNumberField

from reservation.models import Employee, Reservation, Restaurant, Table
from users.forms import StyleFormMixin


class ContactForm(StyleFormMixin, forms.Form):
    """Форма обратной связи"""

    name = forms.CharField(max_length=100, label="Имя")
    email = forms.EmailField(validators=[EmailValidator()], label="Почта")
    phone = PhoneNumberField(required=False, label="Телефон")
    message = forms.CharField(widget=forms.Textarea, label="Сообщение")


class ReservationForm(StyleFormMixin, forms.ModelForm):
    """Форма нового бронирования"""

    class Meta:
        model = Reservation
        exclude = ("customer",)

    def clean_date_reserved(self):
        """Валидация даты бронирования"""
        date_reserved = self.cleaned_data.get("date_reservation")
        today = date.today()

        if date_reserved < today:
            raise ValidationError("Дата бронирования не может быть раньше сегодняшнего дня")

        return date_reserved


class TableForm(StyleFormMixin, forms.ModelForm):
    """Форма для создания и редактирования столиков"""

    class Meta:
        model = Table
        fields = "__all__"


class EmployeeForm(StyleFormMixin, forms.ModelForm):
    """Форма для создания и редактирования столиков"""

    class Meta:
        model = Employee
        fields = "__all__"


class RestaurantForm(StyleFormMixin, forms.ModelForm):
    """Форма для создания и редактирования столиков"""

    class Meta:
        model = Restaurant
        fields = "__all__"

admin_page/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from reservation.forms import EmployeeForm, RestaurantForm
from reservation.models import Employee, Restaurant
from reservation.services import get_statistical_data


class AdminPageViews(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    """Контроллер для отображения страница для администратора сайта"""

    template_name = "admin_page/admin_page.html"
    permission_required = "users.can_change_content"

    def get_context_data(self, **kwargs):
        """Статистические данные"""
        context = super().get_context_data(**kwargs)

        context["data"] = get_statistical_data()
        return context


class EmployeeCreate(LoginRequiredMixin, CreateView):
    """Контроллер создания нового сотрудника"""

    model = Employee
    form_class = EmployeeForm
    template_name = "admin_page/employee_form.html"
    success_url = reverse_lazy("admin_page:employee_list")


class EmployeeDelete(LoginRequiredMixin, DeleteView):
    """Контроллер удаления сотрудника"""

    model = Employee
    form_class = EmployeeForm
    template_name = "admin_page/employee_delete.html"
    success_url = reverse_lazy("admin_page:employee_list")


class EmployeeUpdate(LoginRequiredMixin, UpdateView):
    """Контроллер изменения сотрудников"""

    model = Employee
    form_class = EmployeeForm
    template_name = "admin_page/employee_form.html"
    success_url = reverse_lazy("admin_page:employee_list")


class EmployeeDetail(DetailView):
    """Контроллер детализации сотрудников"""

    model = Employee
    template_name = "admin_page/employee_detail.html"


class EmployeeList(ListView):
    """Контроллер вывода списка столов"""

    model = Employee
    template_name = "admin_page/employee_list.html"
    context_object_name = "employees"


class RestaurantUpdate(LoginRequiredMixin, UpdateView):
    """Контроллер изменения информации о ресторане"""

    model = Restaurant
    form_class = RestaurantForm
    template_name = "admin_page/restaurant_form.html"

    def get_success_url(self):
        return reverse("admin_page:restaurant_detail", args=[self.kwargs.get("pk")])


class RestaurantDetail(DetailView):
    """Контроллер детализации ресторана"""

    model = Restaurant
    template_name = "admin_page/restaurant_detail.html"

reservation/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_GET
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from config.settings import EMAIL_HOST_USER
from reservation.forms import ContactForm, ReservationForm, TableForm
from reservation.models import Employee, Reservation, Restaurant, Table
from reservation.services import get_free_tables


# @method_decorator(cache_page(60 * 3), name="dispatch")
class HomeViews(TemplateView):
    """Контроллер для отображения главной страница сайта"""

    form_class = ContactForm
    template_name = "reservation/home.html"

    def get_context_data(self, **kwargs):
        """Отправка формы в шаблон"""
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class()
        context["restaurant"] = Restaurant.objects.get(id=1)
        return context

    def post(self, request, *args, **kwargs):
        """Обработка post запроса и отправки сообщения менеджеру на почту"""

        form = self.form_class(request.POST)
        if form.is_valid():
            name = self.request.POST.get("name")
            message = self.request.POST.get("message")
            phone = self.request.POST.get("phone")
            email = self.request.POST.get("email")
            send_mail(
                subject="Обратная связь",
                message=f"Здравствуйте, Вам пришло сообщение с сайта ресторана (с формы обратной связи). "
                f"Имя отправителя {name}, сообщение: {message}. "
                f"Связаться можно по тел.: {phone} или почте: {email}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[EMAIL_HOST_USER],
            )
            messages.success(self.request, "Ваше сообщение отправлено менеджеру. В ближайшее время с Вами свяжутся")
            return redirect("reservation:home")
        context = self.get_context_data()
        context["form"] = form
        return self.render_to_response(context)


class AboutRestaurantViews(TemplateView):
    """Контроллер для отображения страница о ресторане"""

    template_name = "reservation/restaurant.html"

    def get_context_data(self, **kwargs):
        """Отправка формы в шаблон"""
        context = super().get_context_data(**kwargs)
        context["restaurant"] = Restaurant.objects.get(id=1)
        context["employees"] = Employee.objects.all()
        return context


class ReservationCreate(LoginRequiredMixin, CreateView):
    """Контроллер нового бронирования столика"""

    model = Reservation
    form_class = ReservationForm
    template_name = "reservation/reservation_form.html"
    success_url = reverse_lazy("reservation:reservation_list")

    def form_valid(self, form):
        reservation = form.save()
        user = self.request.user
        reservation.customer = user
        reservation.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["all_tables"] = Table.objects.all()  # Получаем все столики
        return context


@require_GET
def get_available_tables(request):
    """AJAX-функция для получения доступных столиков"""
    date_str = request.GET.get("date_reservation")
    time_str = request.GET.get("time_reservation")

    if not date_str or not time_str:
        return JsonResponse({"error": "Не указана дата или время"}, status=400)

        # Получаем занятые столики на эту дату и время
    try:
        date = datetime.strptime(date_str, "%Y-%m-%d").date()
        time = datetime.strptime(time_str, "%H:%M").time()
        available_tables = get_free_tables(date, time)
        tables_data = [
            {
                "id": table.id,
                "number": table.table_number,
                "capacity": table.table_capacity,
                "location": table.location or "",
            }
            for table in available_tables
        ]

        return JsonResponse({"tables": tables_data})

    except Exception as e:
        return JsonResponse({"error": str(e)}, status=400)


class ReservationDetail(LoginRequiredMixin, DetailView):
    """Контроллер детализации брони"""

    model = Reservation
    template_name = "reservation/reservation_detail.html"


class ReservationList(LoginRequiredMixin, ListView):
    """Контроллер вывода списка брони"""

    model = Reservation
    template_name = "reservation/reservation_list.html"
    context_object_name = "reservations"
    ordering = ["date_reservation", "time_reservation"]

    def get_queryset(self):
        """Выборка брони по пользователю"""
        queryset = cache.get("reservations_queryset")
        if not queryset:
            queryset = super().get_queryset()
        if not self.request.user.has_perm("users.can_change_content"):
            return queryset.filter(customer=self.request.user.id)
        return Reservation.objects.all()


class ReservationDelete(LoginRequiredMixin, DeleteView):
    """Контроллер удаления брони"""

    model = Reservation
    template_name = "reservation/reservation_delete.html"
    success_url = reverse_lazy("reservation:reservation_list")
    permission_required = "reservation.delete_reservation"


class ReservationUpdate(LoginRequiredMixin, UpdateView):
    """Контроллер изменения бронирования"""

    model = Reservation
    form_class = ReservationForm
    template_name = "reservation/reservation_form.html"
    success_url = reverse_lazy("reservation:reservation_list")

    def get_success_url(self):
        return reverse("reservation:reservation_detail", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["all_tables"] = Table.objects.all()  # Получаем все столики
        return context


@method_decorator(cache_page(60 * 3), name="dispatch")
class TableList(ListView):
    """Контроллер вывода списка столов"""

    model = Table
    template_name = "reservation/table_list.html"
    context_object_name = "tables"


class TableDetail(DetailView):
    """Контроллер детализации столов"""

    model = Table
    template_name = "reservation/table_detail.html"


class TableCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Контроллер создания нового стола"""

    model = Table
    form_class = TableForm
    template_name = "reservation/table_form.html"
    success_url = reverse_lazy("reservation:table_list")
    permission_required = "reservation.add_table"


class TableUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Контроллер изменения стола"""

    model = Table
    form_class = TableForm
    template_name = "reservation/table_form.html"
    success_url = reverse_lazy("reservation:table_list")
    permission_required = "reservation.change_table"

    def get_success_url(self):
        return reverse("reservation:table_detail", args=[self.kwargs.get("pk")])


class TableDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Контроллер удаления столов"""

    model = Table
    template_name = "reservation/table_confirm_delete.html"
    success_url = reverse_lazy("reservation:table_list")
    permission_required = "reservation.delete_table"

reservation/templates/reservation/admin_page.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Админка</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"/>

</head>
<body>
{% include 'reservation/includes/top_menu.html' %}
<div class="container-fluid py-4">
    <div class="row mb-4">
        <div class="col-12">
            <h2><i class="bi bi-speedometer2 me-2"></i> Панель управления</h2>
            <p class="text-muted">Добро пожаловать, {{ user.email }}! Сегодня {% now "j F Y" %}</p>
        </div>
    </div>

    <!-- Статистика -->
    <div class="row mb-4">
        <div class="col-md-4 mb-3">
            <div class="card h-100 stat-card bg-reservations">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div>
                            <h5 class="card-title text-muted">Общие количество бронирований</h5>
                            <h2 class="mb-0">{{ data.reservations_count }}</h2>
                        </div>
                        <div class="icon-stat bg-purple">
                            <i class="bi bi-calendar-check fs-1 text-purple"></i>
                        </div>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'reservation:reservation_list' %}" class="btn btn-sm btn-outline-purple">
                            Управление бронирования<i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 mb-3">
            <div class="card h-100 stat-card bg-tables">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div>
                            <h5 class="card-title text-muted">Количество столиков</h5>
                            <h2 class="mb-0">{{ data.tables_count }}</h2>
                        </div>
                        <div class="icon-stat bg-orange">
                            <i class="bi bi-table fs-1 text-orange"></i>
                        </div>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'reservation:table_list' %}" class="btn btn-sm btn-outline-orange">
                            Управление столиками<i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 mb-3">
            <div class="card h-100 stat-card bg-users">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div>
                            <h5 class="card-title text-muted">Количество зарегистрированных пользователей</h5>
                            <h2 class="mb-0">{{ data.users_count }}</h2>
                        </div>
                        <div class="icon-stat bg-teal">
                            <i class="bi bi-people fs-1 text-teal"></i>
                        </div>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'users:user_list' %}" class="btn btn-sm btn-outline-teal">
                            Управление пользователями<i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Основной контент -->
    <div class="row">
        <!-- Последние бронирования -->
        <div class="col-lg-8 mb-4">
            <div class="card dashboard-card">
                <div class="card-header bg-white">
                    <h5 class="mb-0"><i class="bi bi-clock-history me-2"></i> Последние бронирования</h5>
                </div>
                <div class="card-body recent-orders">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Дата</th>
                                    <th>Столик</th>
                                    <th>Количество гостей</th>
                                    <th>Гость</th>
                                    <th>Действия</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for reservation in data.recent_reservations %}
                                <tr>
                                    <td>{{ reservation.id }}</td>
                                    <td>{{ reservation.date_reservation|date:"d.m.Y" }} {{ reservation.time_reservation|time:"H:i" }}</td>
                                    <td>№{{ reservation.table.table_number }}</td>
                                    <td>№{{ reservation.count_people }}</td>
                                    <td>{{ reservation.customer.email }}</td>
                                    <td>
                                    <a href="{% url 'reservation:reservation_update' reservation.pk %}" class="btn btn-sm btn-outline-primary">
                                            Редактировать
                                        </a>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="6" class="text-center">Нет последних бронирований</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer bg-white">
                    <a href="{% url 'reservation:reservation_list' %}" class="btn btn-sm btn-primary">
                        Все бронирования <i class="bi bi-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>

        <!-- Быстрые действия -->
        <div class="col-lg-4 mb-4">
            <div class="card dashboard-card">
                <div class="card-header bg-white">
                    <h5 class="mb-0"><i class="bi bi-lightning me-2"></i> Быстрые действия</h5>
                </div>
                <div class="card-body">
                    <div class="d-grid gap-2">
                        <a href="{% url 'reservation:reservation_create' %}" class="btn btn-outline-primary text-start">
                            <i class="bi bi-plus-circle me-2"></i> Добавить бронирование
                        </a>
                        <a href="{% url 'reservation:table_create' %}" class="btn btn-outline-secondary text-start">
                            <i class="bi bi-plus-square me-2"></i> Добавить столик
                        </a>
                    </div>
                </div>
            </div>


{% block footer %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 text-center text-muted small">
            <p>Админ-панель ресторана "Сладкая жизнь" &copy; {% now "Y" %}</p>
        </div>
    </div>
</div>
{% endblock %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

reservation/templates/reservation/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ресторан сладкая жизнь</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"/>

</head>
<body>
{% include 'reservation/includes/top_menu.html' %}


<div class="card text-bg-dark border-0 rounded-0" style="height: 60vh;">
  <img src="{% static '/images/backgraund.png' %}" class="card-img h-100" alt="Фон" style="object-fit: cover;">
  <div class="card-img-overlay d-flex flex-column justify-content-center align-items-center text-center" style="background-color: rgba(0,0,0,0.4);">
    <div class="px-3" style="max-width: 800px;">
      <h5 class="card-title display-3 display-md-2 mb-4">{{ restaurant_name }}</h5>
      <p class="card-text lead d-none d-md-block mb-4">{{ restaurant_mission }}</p>
      <a href="{% url 'reservation:reservation_create' %}" class="btn btn-outline-light btn-lg mt-3">Забронировать столик</a>
    </div>
  </div>
</div>
{% block content %}
{% endblock %}

{% include 'reservation/includes/inc_menu.html' %}


<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

reservation/templates/reservation/reservation_detail.html
{% extends 'reservation/base.html' %}
{% load my_tags %}

{% block title %}Информация по бронированию{% endblock %}

{% block content %}
<section class="bg-light p-5 rounded mb-5">
    <h2 class="text-center mb-4">Информация по бронированию Стол №{{ reservation.table.table_number }}</h2>
    <div class="row align-items-center">
        <!-- Блок с информацией (левая колонка) -->
        <div class="col-lg-6">
            <div class="card border-0 bg-transparent">
                <div class="card-body">
                    <p class="fs-5"><i class="bi bi-calendar-check me-2"></i> Дата: {{ reservation.date_reservation|date:"d.m.Y" }}</p>
                    <p class="fs-5"><i class="bi bi-clock me-2"></i> Время: {{ reservation.time_reservation|time:"H:i" }}</p>
                    <p class="fs-5"><i class="bi bi-people me-2"></i> Гостей: {{ reservation.count_people }}</p>
                    <p class="fs-5"><i class="bi bi-stopwatch me-2"></i> Продолжительность: {{ reservation.count_hours }} ч.</p>
                    {% if reservation.wishes %}
                    <p class="fs-5"><i class="bi bi-chat-left-text me-2"></i> Пожелания: {{ reservation.wishes }}</p>
                    {% endif %}

                    <div class="mt-4">
                        <a href="{% url 'reservation:reservation_list' %}" class="btn btn-primary me-2">
                            <i class="bi bi-list"></i> К списку бронирований
                        </a>

                        {% load tz %}
                        {% now "Y-m-d" as current_date %}
                        {% now "H:i" as current_time %}

                        {% with reservation_date=reservation.date_reservation|date:"Y-m-d" %}
                            {% if reservation_date > current_date or reservation_date == current_date and reservation.time_reservation|time:"H:i" > current_time|add:"1:00" %}
                        <a href="{% url 'reservation:reservation_update' reservation.pk %}" class="btn btn-secondary">
                            <i class="bi bi-list"></i> Редактировать
                        </a>
                        {% endif %}
                        {% endwith %}
                        <a href="{% url 'reservation:reservation_delete' reservation.pk %}" class="btn btn-danger">
                            <i class="bi bi-trash"></i> Удалить
                        </a>

                    </div>
                </div>
            </div>
        </div>

        <!-- Блок с изображением (правая колонка) -->
        <div class="col-lg-6 text-center">
            <img src="{{ reservation.table.photo_table | media_filter }}"
                 class="img-fluid rounded shadow-lg"
                 alt="Стол №{{ reservation.table.table_number }}"
                 style="max-height: 400px; object-fit: cover;">
            <h3 class="mt-3 text-primary">Будем рады видеть Вас у нас!</h3>
        </div>
    </div>
</section>

{% endblock %}

reservation/templates/reservation/table_detail.html
{% extends 'reservation/base.html' %}
{% load my_tags %}

{% block title %}Информация по столам{% endblock %}

{% block content %}
<section class="bg-light p-5 rounded mb-5">
     <div class="text-center">  <!-- Добавленный контейнер с выравниванием по центру -->
        <h2>Стол №{{ table.table_number }}</h2>
    </div>
     <div class="row justify-content-center">
            <div class="col-lg-8">
                <img class="card-img-top" src="{{ table.photo_table | media_filter }}" alt="Card image cap"  style="max-width: 300px; height: auto;">
                <p>Расположение: {{ table.location }}</p>
                <p>Вместительность стола: {{ table.table_capacity }} чел.</p>

                <a href="{% url 'reservation:table_list' %}" class="btn btn-primary">Вернуться к списку</a>
                {% if perms.users.can_change_content %}
                <a href="{% url 'reservation:table_update' table.pk %}" class="btn btn-secondary">Редактировать</a>
                <a href="{% url 'reservation:table_delete' table.pk %}" class="btn btn-danger">Удалить</a>
                {% endif %}

            </div>
        </div>
    </section>
{% endblock %}

reservation/templates/reservation/table_list.html
{% extends 'reservation/base.html' %}
{% load my_tags %}
{% block title %}Список столов{% endblock %}

{% block content %}

<div class="text-center">
<h2>Список столов</h2>
    </div>
<div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for table in tables %}
            <div class="col-3">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header">
                    <img class="card-img-top" src="{{ table.photo_table | media_filter }}" alt="Card image cap"  style="max-width: 300px; height: auto;">
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">Стол № {{ table.table_number }}</h3>
                    <p>Вместимость: {{ table.table_capacity }} </p>
                    <p>Расположение столика: {{ table.location }} </p>
                    {% if perms.users.can_change_content %}
                    <a class="btn btn-primary" href="{% url 'reservation:table_detail' table.pk %}" role="button">Подробнее</a>
                    {% endif %}
                </div>
            </div>

            </div>
            {% endfor %}
    </div>

</div>
{% if perms.users.can_change_content %}

<p>

    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">

        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'reservation:table_create' %}">Добавить новый стол</a>

    </div>

</p>
   {% endif %}
{% endblock %}