config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
    path("", include("reservation.urls", namespace="reservation")),
    path("admin_page/", include("admin_page.urls", namespace="admin_page")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reservation/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from reservation.apps import ReservationConfig
from reservation.views import (AboutRestaurantViews, HomeViews, ReservationCreate, ReservationDelete,
                               ReservationDetail, ReservationList, ReservationUpdate, TableCreate, TableDelete,
                               TableDetail, TableList, TableUpdate, get_available_tables)

app_name = ReservationConfig.name

urlpatterns = [
    path("", HomeViews.as_view(), name="home"),
    path("restaurant/", cache_page(60 * 10)(AboutRestaurantViews.as_view()), name="restaurant"),
    path("reservation/create/", ReservationCreate.as_view(), name="reservation_create"),
    path("reservation/<int:pk>/", ReservationDetail.as_view(), name="reservation_detail"),
    path("reservation/<int:pk>/update/", ReservationUpdate.as_view(), name="reservation_update"),
    path("reservation/<int:pk>/delete/", ReservationDelete.as_view(), name="reservation_delete"),
    path("reservation/", ReservationList.as_view(), name="reservation_list"),
    path("tables/", TableList.as_view(), name="table_list"),
    path("table/<int:pk>/", TableDetail.as_view(), name="table_detail"),
    path("table/create/", TableCreate.as_view(), name="table_create"),
    path("table/<int:pk>/delete/", TableDelete.as_view(), name="table_delete"),
    path("table/<int:pk>/update/", TableUpdate.as_view(), name="table_update"),
    path("get-available-tables/", get_available_tables, name="get_available_tables"),
]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordResetDoneView, PasswordResetView)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import (BlockUsersView, UserCreateViews, UserDelete, UserDetail, UserList, UserUpdateViews,
                         email_verification)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateViews.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("users/<int:pk>/update", UserUpdateViews.as_view(), name="user_update"),
    path("users/<int:pk>/delete", UserDelete.as_view(), name="user_delete"),
    path("users/<int:pk>/", UserDetail.as_view(), name="user_detail"),
    path("users/", UserList.as_view(), name="user_list"),
    path("users/<int:pk>/block_user", BlockUsersView.as_view(), name="block_user"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    """Модель пользователь"""

    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone = PhoneNumberField(
        verbose_name="Телефон", null=True, blank=True, help_text="Введите номер телефона", region="RU"
    )
    avatar = models.ImageField(
        upload_to="users/avatars", verbose_name="Аватар", null=True, blank=True, help_text="Загрузите свой аватар"
    )
    tg_name = models.CharField(
        max_length=50, verbose_name="Телеграм-ник", null=True, blank=True, help_text="Введите телеграм-ник"
    )
    token = models.CharField(max_length=100, verbose_name="Token", null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_change_content", "Can change content"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.forms import BooleanField

from users.models import User


class StyleFormMixin:
    """Стилизация форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"
            if field_name == "phone":
                field.widget.attrs.update({"placeholder": "+7 (XXX) XXX-XX-XX"})
            if field_name == "date_reservation":
                field.widget = forms.DateInput(
                    attrs={
                        "type": "date",
                        "class": "form-control datepicker",
                        "min": datetime.now().strftime("%Y-%m-%d"),
                    },
                    format="%Y-%m-%d",
                )
            if field_name == "time_reservation":
                field.widget = forms.TimeInput(
                    attrs={
                        "type": "time",
                        "class": "form-control timepicker",
                        "step": "300",
                        "min": "10:00",  # Минимальное время
                        "max": "23:00",  # Максимальное время
                    }
                )


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации пользователя"""

    username = None

    class Meta:
        model = User
        fields = ("email", "phone", "avatar", "tg_name", "password1", "password2")


class UserUpdateForm(StyleFormMixin, UserChangeForm):
    """Форма изменения профиля пользователя"""

    username = None

    class Meta:
        model = User
        fields = ("email", "phone", "avatar", "tg_name", "last_name", "first_name")

users/views.py
import secrets

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, View

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User


class UserCreateViews(CreateView):
    template_name = "users/register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение почты",
            message=f"Здравствуйте, для регистрации почты {url} перейдите по ссылке",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        messages.success(self.request, "Письмо с подтверждением отправлено на ваш email.")
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.token = None
    user.is_active = True
    user.save()
    messages.success(request, "Ваш email успешно подтверждён!")
    return redirect(reverse("users:login"))


class UserUpdateViews(LoginRequiredMixin, UpdateView):
    template_name = "users/register.html"
    form_class = UserUpdateForm
    success_url = reverse_lazy("users:login")

    def get_queryset(self):
        return User.objects.filter(id=self.request.user.id)

    def get_success_url(self):
        return reverse("users:user_detail", args=[self.kwargs.get("pk")])


class UserDetail(DetailView):
    """Контроллер вывода списка сообщений"""

    model = User
    template_name = "users/user_detail.html"
    context_object_name = "user"


class UserList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """Контроллер вывода списка сообщений"""

    model = User
    template_name = "users/users_list.html"
    context_object_name = "users"
    permission_required = "users.view_user"

    def get_queryset(self):
        """Исключение из списка суперпользователя и всех менеджеров"""
        queryset = super().get_queryset()
        queryset = queryset.filter(is_superuser=False)
        # Исключаем пользователей с правами can_change_content
        queryset = queryset.exclude(groups__permissions__codename="can_change_content")
        return queryset


class UserDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Контроллер удаления столов"""

    model = User
    template_name = "users/user_confirm_delete.html"
    success_url = reverse_lazy("user:user_list")
    permission_required = "users.delete_user"


class BlockUsersView(LoginRequiredMixin, View):

    def post(self, request, pk):
        user = get_object_or_404(User, id=pk)

        if user.is_active:
            user.is_active = False
        else:
            user.is_active = True

        user.save()

        return redirect("users:user_list")

users/templates/users/login.html
{% extends 'reservation/base.html' %}

{% block content %}

<section class="bg-light p-5 rounded mb-5">
    <div class="row justify-content-center">
            <div class="col-lg-8">
 {% if messages %}
          {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
         {% endfor %}
      <a href="{% url 'users:login' %}">Войти</a>
    {% else %}

       <form class="row" method="post" enctype="multipart/form-data">
           <div class="col-6">
         <div class="card">
            <div class="card-body">
                 {% csrf_token %}
                {{ form.as_p }}
             </div>
             <button type="submit" class="btn btn-primary">
                Войти
             </button>
         </div>
  </div>
    </form>
<p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
{% endif %}



  </div>
</div>
    </section>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'reservation/base.html' %}

{% block content %}
<h2>Сброс пароля</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'reservation/base.html' %}

{% block content %}
<h2>Пароль успешно изменён</h2>
<p>Ваш пароль был изменён. Теперь вы можете <a href="{% url 'users:login' %}">войти</a>.</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'reservation/base.html' %}
{% block content %}
<h2>Введите новый пароль</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сменить пароль</button>
</form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'reservation/base.html' %}

{% block content %}
<h2>Письмо отправлено</h2>
<p>Мы отправили вам инструкции по сбросу пароля на ваш email.</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% trans "Ваше имя пользователя, если вы забыли::" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

users/templates/users/register.html
{% extends 'reservation/base.html' %}
{% load my_tags %}
{% block content %}

<section class="bg-light p-5 rounded mb-5">
    <div class="row justify-content-center">
            <div class="col-lg-8">

       <form class="row" method="post" enctype="multipart/form-data">
           <div class="col-6">
         <div class="card">
            <div class="card-body">
                 {% csrf_token %}
                {{ form.as_p }}

             </div>
            <button type="submit" class="btn btn-primary">
                {% if object %}
                 Сохранить
                 {% else %}
                 Зарегестрироваться
                {% endif %}
             </button>
         </div>
  </div>

    </form>

  </div>

 </div>

    </section>

{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'reservation/base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-6">
       <form class="row" method="post" enctype="multipart/form-data">
         <div class="card">
              <p class="card-text">Действительно хотите удалить пользователя {{ object.email }}</p>
             <div class="card-body">
                 {% csrf_token %}
             </div>
             <button type="submit" class="btn btn-primary">
                 Удалить
             </button>
             <a class="btn btn-primary" href="{% url 'users:user_list'%}" role="button">Отмена</a>
         </div>
        </form>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'reservation/base.html' %}
{% load my_tags %}
{% block title %} Личный кабинет{% endblock %}

{% block content %}
<section class="bg-light p-5 rounded mb-5">
    <h2 class="text-center mb-4">Пользователь: {{ user.email }}</h2>
    <div class="row justify-content-center">
            <div class="col-lg-8">
                <img class="card-img-top" src="{{ user.avatar | media_filter }}" alt="Аватар">
                <p>Телефон: {{ user.phone }}</p>
                <p>Телеграмм: {{ user.tg_name }}</p>
                <p>Фамилия: {{ user.last_name }}</p>
                <p>Имя: {{ user.first_name }}</p>
                {% if not perms.users.can_change_content %}
                <a href="{% url 'users:user_update' user.pk %}" class="btn btn-primary">Редактировать</a>
                {% endif %}
                <a href="{% url 'reservation:reservation_list' %}" class="btn btn-primary">История бронирования</a>
                {% if perms.users.can_change_content %}
                <a href="{% url 'users:user_list' %}" class="btn btn-primary">Вирнуться к списку</a>
                {% endif %}
            </div>
    </div>

</section>
{% endblock %}

users/templates/users/users_list.html
{% extends 'reservation/base.html' %}

{% block content %}
<h2>Список пользователей</h2>
<ul class="list-group">
    {% for user in users %}
        <li class="list-group-item">
            {{ user.id }}
            {{ user.email }}
           <div class="d-flex gap-2">
    <a href="{% url 'users:user_detail' user.pk %}" class="btn btn-primary">Подробнее</a>

    <form action="{% url 'users:block_user' user.pk %}" method="post" class="d-inline">
        {% csrf_token %}
        {% if user.is_active %}
            <button type="submit" class="btn btn-warning">Заблокировать</button>
        {% else %}
            <button type="submit" class="btn btn-success">Разблокировать</button>
        {% endif %}
    </form>

    <form action="{% url 'users:user_delete' user.pk %}" method="post" class="d-inline">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>
        </li>
    {% endfor %}
</ul>

{% endblock %}